#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "USERNAME/PASSWORD@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=HOST)(Port=PORT))(CONNECT_DATA=(SID=orcl)))" <<EOF

DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE ADVERTISEMENT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_INFO CASCADE CONSTRAINTS;
DROP TABLE DRIVER CASCADE CONSTRAINTS;
DROP TABLE TRIP CASCADE CONSTRAINTS;
DROP TABLE TRIP_HISTORY CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE RIDE CASCADE CONSTRAINTS;
exit;
EOF
